name: Publish

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Compile LaTeX sources
              uses: xu-cheng/latex-action@2.2.1
              with:
                  pre_compile: tlmgr update --self && tlmgr update --all
                  work_in_root_file_dir: true
                  root_file: |
                      tex/analysis_2/analysis_2.tex
            - name: Move PDFs
              run: mv ./*.pdf dist
              shell: bash
            - name: Move index page
              run: cp README.md dist/index.md
              shell: bash
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3.8.0
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: dist
                  allow_empty_commit: true
                  force_orphan: true
                  enable_jekyll: true
