name: Publish

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
              with:
                  submodules: true
            - name: Compile LaTeX sources
              uses: xu-cheng/latex-action@3.1.0
              with:
                  pre_compile: tlmgr update --self && tlmgr update --all
                  work_in_root_file_dir: true
                  latexmk_use_lualatex: true # This is needed to compile the root.tex file
                  root_file: |
                      tex/analysis_2/analysis_2.tex
                      tex/bubbles/bubbles.tex
                      tex/cavendish/cavendish.tex
                      tex/fnad/fnad.tex
                      tex/maxwell/maxwell.tex
                      tex/particles/particles.tex
                      tex/thermocouple/thermocouple.tex
                      tex/root/root.tex
            - name: Move PDFs
              run: mv ./tex/*/*.pdf dist
              shell: bash
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3.9.3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: dist
                  allow_empty_commit: true
                  force_orphan: true
                  enable_jekyll: true
